import './globals.css'
import {ClusterProvider} from '@/app/context/cluster-data-access'
import {SolanaProvider} from '@/app/context/solana-provider'
import {ReactQueryProvider} from './react-query-provider'
import { PageProvider } from './context/AppContext'

export const metadata = {
  title: 'PARTPAY',
  description: 'Generated by create-solana-dapp',
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <PageProvider>
                {children}
              </PageProvider>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
